import fs from "node:fs/promises";
import path from "node:path";
import { parseArgs } from "node:util";
import { globby } from "globby";
import { camelCase, upperFirst } from "es-toolkit";
import { extractExportedConsts } from "../utils/ast";

export interface GenerateServicesOptions {
    baseDirectory: string;
    zodImport: string;
    watch: boolean;
}

export function parseGenerateServicesArgs(
    args: string[],
): GenerateServicesOptions {
    const { values } = parseArgs({
        args,
        options: {
            "base-directory": { type: "string", default: "src" },
            "zod-import": { type: "string", default: "zod/v4" },
            watch: { type: "boolean", default: false },
        },
        strict: true,
    });
    return {
        baseDirectory: values["base-directory"]!,
        zodImport: values["zod-import"]!,
        watch: values.watch!,
    };
}

function toPascalCase(dirName: string): string {
    return upperFirst(camelCase(dirName));
}

function toServiceDefName(dirName: string): string {
    const pascalCase = toPascalCase(dirName);
    const baseName = pascalCase.endsWith("Service")
        ? pascalCase.slice(0, -7)
        : pascalCase;
    return `${baseName}ServiceDef`;
}

function toServiceTypeName(dirName: string): string {
    const pascalCase = toPascalCase(dirName);
    const baseName = pascalCase.endsWith("Service")
        ? pascalCase.slice(0, -7)
        : pascalCase;
    return `${baseName}Service`;
}

async function runGeneration(opts: GenerateServicesOptions) {
    const serviceRootPatterns = [`${opts.baseDirectory}/**/methods.ts`];

    const methodsFiles = await globby(serviceRootPatterns, {
        absolute: false,
    });
    console.log("Method files:", methodsFiles);

    for (const methodsPath of methodsFiles) {
        const serviceDir = path.basename(path.dirname(methodsPath));
        const serviceDirPath = path.dirname(methodsPath);
        const dtoPath = path.join(serviceDirPath, "dto.ts");

        const methodsContent = await fs
            .readFile(methodsPath, "utf8")
            .catch(e => {
                if (e.code === "ENOENT") return null;
                throw e;
            });
        const dtoStat = await fs.stat(dtoPath).catch(e => {
            if (e.code === "ENOENT") return null;
            throw e;
        });
        if (!methodsContent) continue;
        const consts = extractExportedConsts(methodsContent);

        const lines: string[] = [
            "/* eslint-disable */",
            "/** DO NOT MODIFY: Generated by ts-json-rpc task */",
            `import * as z from "${opts.zodImport}";`,
            'import type { ZServiceType } from "@lorefnon/ts-json-rpc/lib/zod";',
            'import { ZService } from "@lorefnon/ts-json-rpc/lib/zod";',
        ];

        const imports: string[] = [];
        for (const constName in consts) {
            imports.push(constName);
        }
        if (imports.length) {
            lines.push(
                `import {\n${imports.map(_ => `    ${_},`).join("\n")}\n} from "./methods";`,
            );
        }

        const serviceDefName = toServiceDefName(serviceDir);
        const serviceTypeName = toServiceTypeName(serviceDir);

        lines.push(
            "",
            `export const ${serviceDefName} = ZService.define(() => ({`,
        );
        const extraneous: string[] = [];
        const methods: string[] = [];
        Object.entries(consts).forEach(([constName, { req, res }]) => {
            if (constName.charAt(0).toUpperCase() === constName.charAt(0)) {
                extraneous.push(constName);
                return;
            }

            methods.push(constName);
            lines.push(`    ${constName}: z.function({`);
            if (req)
                lines.push(`        input: [${upperFirst(constName)}Req],`);
            if (res) lines.push(`        output: ${upperFirst(constName)}Res,`);
            else lines.push(`        output: z.promise(z.void()),`);
            lines.push(`    }),`);
        });
        lines.push(
            "}));",
            "",
            `export interface ${serviceTypeName} extends ZServiceType<typeof ${serviceDefName}> {}`,
        );

        for (const constName of methods) {
            lines.push("");
            const tPrefix = upperFirst(constName);
            if (consts[constName].req) {
                lines.push(
                    `export interface ${tPrefix}Req extends z.output<typeof ${constName}.req> {}`,
                );
                lines.push(
                    `export interface ${tPrefix}ReqIn extends z.input<typeof ${constName}.req> {}`,
                );
            }
            if (consts[constName].res) {
                lines.push(
                    `export interface ${tPrefix}Res extends z.output<typeof ${constName}.res> {}`,
                );
                lines.push(
                    `export interface ${tPrefix}ResIn extends z.input<typeof ${constName}.res> {}`,
                );
            }
            if (consts[constName].req) {
                lines.push(`export const ${tPrefix}Req = ${constName}.req;`);
            }
            if (consts[constName].res) {
                lines.push(`export const ${tPrefix}Res = ${constName}.res;`);
            }
        }

        if (extraneous.length) {
            lines.push("");
            lines.push(`export { ${extraneous.join(", ")} }`);
        }

        if (dtoStat?.isFile()) {
            lines.push("");
            lines.push(`export * from "./dto";`);
        }
        const outputPath = path.join(serviceDirPath, "def.ts");
        await fs.writeFile(outputPath, lines.join("\n"), "utf8");
        console.log(`Overwritten: ${outputPath}`);
    }
}

export async function generateServices(opts: GenerateServicesOptions) {
    await runGeneration(opts);
    if (!opts.watch) return;

    console.log(`Watching ${opts.baseDirectory} for changes...`);
    const watcher = fs.watch(opts.baseDirectory, { recursive: true });
    let timer: NodeJS.Timeout | null = null;
    for await (const event of watcher) {
        if (!event.filename?.endsWith("methods.ts")) continue;
        if (timer) clearTimeout(timer);
        timer = setTimeout(() => {
            timer = null;
            runGeneration(opts).catch(e => {
                console.error("Generation failed:", e);
            });
        }, 100);
    }
}
